services:
  backend:
    image: henopz/bend:latest
    ports:
      - 3000:80
    networks:
      - my_network
    restart: always
  app:
    image: henopz/fend:latest
    ports:
      - 8080:8081
    depends_on:
      - backend
    networks:
      - my_network
networks:
  my_network:
    driver: bridge