name: "Build Reusable Workflow For Node app"

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  build:
    name: Build Next App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: HenOpz/f_end/.github/prepare-action@main

      - name: build
        run:  |
          npm run build

      - name: Cache the app dependencies
        uses: actions/cache@v4.0.2
        with:
          path: dist
          key: ${{ runner.os }}-node-app