name: "CI Workflow"
on:
    push:
    pull_request:
      branches:
        - dev
        - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    uses: HenOpz/f_end/.github/workflows/build.yaml@main
    with:
      node-version: '20'

  test:
    name: Test
    needs: [build]
    uses: HenOpz/f_end/.github/workflows/test.yaml@main
    with:
      node-version: '20'

  # sec:
  #   name: Sec Check
  #   needs: [test]
  #   uses: HenOpz/f_end/.github/workflows/security.yaml@main
  #   secrets:
  #     GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # push:
  #   name: Push
  #   needs: [test]
  #   uses: HenOpz/f_end/.github/workflows/push.yaml@main
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # deploy:
  #   name: Deploy
  #   # needs: [push]
  #   uses: HenOpz/f_end/.github/workflows/deploy.yaml@main
  #   secrets:
  #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}