name: Kubernetes Deployment
on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH for GitHub Actions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 54.251.159.214 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    # - name: Deploy application
    #   run: |
    #     ssh -o StrictHostKeyChecking=no ubuntu@18.143.141.193 << 'EOF'
    #       sudo apt update
    #       sudo 
          
    #     EOF

    - name: Run Docker container
      run: |
        docker run -d -p 80:80 --name web-svr nginx:latest
      