name: Push Docker image

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Docker Build
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build Docker image
        id: build
        run: |
          docker build -t mydockerimage:latest .
          docker save mydockerimage:latest > image.tar

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Docker image tarball with Trivy
        id: trivy_scan
        run: |
          trivy --format json --output trivy_results.json image.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load Docker image from tarball
        run: docker load < image.tar

      - name: Tag Docker image
        run: docker tag mydockerimage:latest ${{ secrets.DOCKERHUB_USERNAME }}/app:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/app:latest

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy_results.json