name: Push Docker image

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  push:
    name: Build, Scan with Trivy, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build Docker image
        run: |
          docker build -t mydockerimage:latest .
          docker save mydockerimage:latest > image.tar

      - name: Scan Docker image with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: mydockerimage:latest
          format: table # Specify the format of Trivy output (table, json, etc.)

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load Docker image from tarball
        run: docker load < image.tar

      - name: Tag Docker image
        run: docker tag mydockerimage:latest ${{ secrets.DOCKERHUB_USERNAME }}/mydockerimage:latest

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mydockerimage:latest
