name: SonarQube Security Scan

on:
  workflow_call:
    secrets:
      GIT_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
    inputs:
      node-version:
        required: true
        type: string

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: HenOpz/f_end/.github/prepare-action@main
        with:
          node-version: ${{ inputs.node-version }}   

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}